"use client";
import React, {useState} from "react";
import Link from "next/link";
import {ArrowRight, Check, FileText, MessageSquare, ShieldCheck, Truck, Zap} from "lucide-react";
import {Logo, Button, Card, Badge} from "../components/ui";

export default function Landing(){
 const [annual,setAnnual]=useState(true);
 return <div>
  <header className="sticky top-0 z-40 border-b border-line/80 bg-paper/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Logo/><nav className="hidden items-center gap-7 text-sm text-muted md:flex"><a href="#product">Product</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="flex items-center gap-2"><Link className="hidden px-3 py-2 text-sm font-semibold md:block" href="/login">Log in</Link><Button href="/signup">Start free <ArrowRight size={16}/></Button></div></div></header>
  <main>
   <section className="grain blueprint"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 md:grid-cols-[1.05fr_.95fr] md:py-28"><div className="reveal"><Badge tone="success">Built for the factory floor</Badge><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] tracking-tight md:text-7xl">Know which late delivery will stop your line, before it does.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted">Sentinel links purchase orders, delivery notes and invoices, then turns supplier delays into one clear production decision.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/signup">Start free <ArrowRight size={16}/></Button><Button href="/alerts/a1" variant="secondary">See a sample alert</Button></div><p className="mt-4 text-xs text-muted">No card required · Approval stays with you</p></div><div><Card className="relative rotate-1 p-6 shadow-lift"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-muted">Production-critical</p><h3 className="mt-2 text-lg font-semibold">PO-2291 can stop the sheet-metal line</h3></div><Badge tone="critical">Critical</Badge></div><div className="mt-5 rounded-xl bg-paper p-4"><div className="flex justify-between text-sm"><span>Runway</span><strong>3 days</strong></div><div className="mt-2 h-2 rounded-full bg-line"><div className="h-full w-[24%] rounded-full bg-critical"/></div><div className="mt-3 flex justify-between text-xs text-muted"><span>Supplier delay</span><span>+6 days</span></div></div><div className="mt-5 border-l-2 border-primary pl-4 text-sm"><p className="font-semibold">Evidence chain</p><p className="mt-1 text-muted">Delivery note → promised date → supplier history → runway calculation</p></div><div className="mt-5 rounded-xl border border-line p-3 text-sm"><span className="font-semibold">Next step:</span> Request partial dispatch today and confirm balance date.</div><div className="mt-4 flex gap-2"><Button href="/alerts/a1">Review</Button><Button variant="secondary">Modify</Button></div></Card></div></div></section>
   <section className="border-y border-line bg-panel"><div className="mx-auto max-w-7xl px-5 py-8"><div className="grid gap-5 text-sm md:grid-cols-4"><div><p className="font-semibold">Email attachments</p><p className="mt-1 text-muted">POs buried in threads.</p></div><div><p className="font-semibold">WhatsApp photos</p><p className="mt-1 text-muted">Delivery notes on phones.</p></div><div><p className="font-semibold">Tally files</p><p className="mt-1 text-muted">Invoices without context.</p></div><div className="font-semibold text-primary">→ One order timeline</div></div></div></section>
   <section id="product" className="mx-auto max-w-7xl px-5 py-20 md:py-28"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">The evidence chain</p><h2 className="mt-3 font-display text-4xl md:text-5xl">Every warning shows its work.</h2><p className="mt-4 leading-7 text-muted">No black-box alarm. Follow the document, extracted field, supplier history, stock runway and proposed action in one place.</p></div><div className="mt-12 grid gap-4 md:grid-cols-5">{["Raw document","Extracted field","Supplier history","Runway calculation","Recommended action"].map((x,i)=><Card key={x} className="p-5"><div className="text-xs font-bold text-primary">0{i+1}</div><div className="mt-8 font-semibold">{x}</div><p className="mt-2 text-sm text-muted">{["Delivery_Note_PO2291.jpg","Promised date · 28 Sep · 94%","72% on-time · 2.8d variance","3d runway vs +6d delay","Request partial dispatch today"][i]}</p></Card>)}</div></section>
   <section className="bg-ink py-20 text-paper"><div className="mx-auto max-w-7xl px-5"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">One control room</p><h2 className="mt-3 font-display text-4xl">Useful on a busy Tuesday, not just in a demo.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Feature icon={MessageSquare} title="WhatsApp delivery-note capture" text="Send a photo from the store. Sentinel extracts it and asks for confirmation only when needed."/><Feature icon={FileText} title="PO / GRN / invoice matching" text="Line items stay linked so quantity, rate and duplicate-invoice mismatches surface together."/><Feature icon={Truck} title="Supplier scorecards" text="On-time rate, lead-time variance and quality issues in one practical view."/><Feature icon={Zap} title="Runway vs. delay" text="See whether a supplier delay actually crosses the material's production runway."/><Feature icon={ShieldCheck} title="Weekly digest" text="Quiet alerts stay quiet. The owner gets a short list of what needs attention."/><Feature icon={Check} title="Approve / modify / reject" text="Nothing is sent externally without a human approval and an audit trail."/></div></div></section>
   <section id="how" className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-10 md:grid-cols-3">{[["01","Send documents","Forward an email, upload a file or capture a delivery note on the phone."],["02","Sentinel reconciles","Documents are linked to POs and checked against supplier and stock context."],["03","You approve one action","Review the evidence, edit the draft message if needed, then approve."]].map(x=><div key={x[0]} className="border-t-2 border-primary pt-5"><div className="font-display text-4xl text-primary">{x[0]}</div><h3 className="mt-5 text-xl font-semibold">{x[1]}</h3><p className="mt-2 leading-7 text-muted">{x[2]}</p></div>)}</div></section>
   <section className="border-y border-line bg-panel"><div className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-8 md:grid-cols-3"><div><ShieldCheck className="text-primary"/><h3 className="mt-4 font-semibold">Privacy by design</h3><p className="mt-2 text-sm leading-6 text-muted">See which data is sent to the configured AI provider. Local-model deployment remains an option for sensitive operations.</p></div><div><h3 className="font-semibold">Human approval</h3><p className="mt-2 text-sm leading-6 text-muted">Sentinel recommends. Your team decides. Outbound supplier messages require approval.</p></div><div><h3 className="font-semibold">India-ready</h3><p className="mt-2 text-sm leading-6 text-muted">Designed with DPDP Act considerations, configurable retention and an audit trail for operational decisions.</p></div></div></div></section>
   <section id="pricing" className="mx-auto max-w-7xl px-5 py-20"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Pricing</p><h2 className="mt-3 font-display text-4xl">Start small. Add volume when it helps.</h2><div className="mt-5 inline-flex rounded-full border border-line bg-panel p-1 text-sm"><button className={annual?"rounded-full bg-primary px-4 py-2 text-paper":"rounded-full px-4 py-2 text-muted"} onClick={()=>setAnnual(true)}>Annual</button><button className={!annual?"rounded-full bg-primary px-4 py-2 text-paper":"rounded-full px-4 py-2 text-muted"} onClick={()=>setAnnual(false)}>Monthly</button></div></div><div className="mx-auto mt-10 grid max-w-4xl gap-5 md:grid-cols-3"><Price name="Pilot" price={annual?"₹2,490":"₹2,990"} text="For a small procurement desk" items={["Up to 50 open POs","Document ingestion","Evidence alerts"]}/><Price name="Factory" price={annual?"₹5,990":"₹6,990"} featured text="For active production" items={["Up to 250 open POs","Supplier scorecards","Runway risk","Approval workflow"]}/><Price name="Operations" price="Custom" text="For multi-site teams" items={["Unlimited sources","ERP / Tally connectors","Local-model option","Priority support"]}/></div></section>
   <section id="faq" className="border-t border-line bg-panel"><div className="mx-auto max-w-4xl px-5 py-20"><h2 className="font-display text-4xl">Questions owners ask.</h2><div className="mt-8 space-y-3">{[["Will Sentinel send messages automatically?","No. Recommendations can draft the next message, but external actions stay behind human approval."],["What documents can I start with?","Purchase orders, delivery notes, invoices and stock summaries. Email forwarding and WhatsApp capture can be connected during onboarding."],["Does this replace Tally?","No. Sentinel is the operational risk layer. ERP/Tally connectors can be added later."],["Can data stay in India or on-prem?","The product supports a local-model path for deployments where documents should not leave the controlled environment."]].map(x=><details key={x[0]} className="group rounded-xl border border-line bg-paper p-5"><summary className="cursor-pointer list-none font-semibold">{x[0]} <span className="float-right">+</span></summary><p className="mt-3 text-sm leading-6 text-muted">{x[1]}</p></details>)}</div></div></section>
   <section className="mx-auto max-w-7xl px-5 py-20"><Card className="bg-primary p-8 text-paper md:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="text-xs uppercase tracking-[.18em] opacity-70">First run</p><h2 className="mt-2 font-display text-4xl">Get your first production-critical alert in place.</h2><p className="mt-3 max-w-xl text-sm leading-6 opacity-80">Load sample data first. Replace it with your documents when the team is ready.</p></div><Button href="/signup" variant="secondary">Start free <ArrowRight size={16}/></Button></div></Card></section>
  </main>
  <footer className="border-t border-line px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-muted md:flex-row md:items-center md:justify-between"><Logo/><span>© 2026 SupplyChain Sentinel · Calm decisions for busy factories.</span></div></footer>
 </div>
}
function Feature({icon:Icon,title,text}:any){return <Card className="border-paper/10 bg-paper/5 p-5 text-paper shadow-none"><Icon size={19} className="text-primary"/><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-paper/60">{text}</p></Card>}
function Price({name,price,text,items,featured=false}:any){return <Card className={featured?"border-primary p-6 ring-2 ring-primary/15":"p-6"}>{featured&&<Badge tone="success">Most used</Badge>}<h3 className="mt-2 font-semibold">{name}</h3><p className="mt-2 text-sm text-muted">{text}</p><div className="mt-6 font-display text-4xl">{price}<span className="text-sm text-muted"> / month</span></div><ul className="mt-6 space-y-3 text-sm">{items.map((x:string)=><li key={x} className="flex gap-2"><Check size={16} className="mt-0.5 text-success"/>{x}</li>)}</ul><Button href="/signup" className="mt-7 w-full">Start free</Button></Card>}
