"use client";
import {ClipboardList,PackageCheck,ShieldCheck,Timer,Upload,ArrowRight} from "lucide-react";
import {AppShell,AlertCard,Button,Card,DataTable,Metric,RunwayBar,SectionHeading,StatusPill} from "../../components/ui";
import {alerts,dashboard,orders} from "../../lib/fixtures";
import PerformanceChart from "../../components/performance-chart";
export default function Dashboard(){return <AppShell title="Good evening, Dhairya." subtitle="Monday · 29 September 2026 · Procurement control room">
<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Orders at risk" value={dashboard.ordersAtRisk} sub="Need attention today" icon={ClipboardList} tone="critical"/><Metric label="Production-critical" value={dashboard.productionCritical} sub="Could stop a line" icon={Timer} tone="critical"/><Metric label="Awaiting approval" value={dashboard.awaitingApproval} sub="Recommended actions" icon={ShieldCheck}/><Metric label="On-time rate" value={dashboard.onTimeRate+"%"} sub="Last 30 supplier receipts" icon={PackageCheck}/></div>
<div className="mt-10 grid gap-8 xl:grid-cols-[1.25fr_.75fr]"><section><SectionHeading eyebrow="Business impact" title="What needs your attention" description="Only production-critical warnings are visually loud. Everything else stays quiet until it matters." action={<Button href="/capture" variant="secondary"><Upload size={16}/> Add documents</Button>}/><div className="space-y-3">{alerts.map(a=><AlertCard key={a.id} alert={a}/>)}</div></section><section><SectionHeading eyebrow="Open orders" title="Delivery runway" description="A short runway matters only when it crosses the predicted delay."/><Card className="divide-y divide-line">{orders.map(o=><div key={o.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-muted">{o.po}</p><p className="mt-1 font-semibold">{o.material}</p><p className="mt-1 text-xs text-muted">{o.supplier}</p></div><StatusPill risk={o.risk}/></div><div className="mt-4"><RunwayBar days={o.runway} delay={o.delay}/></div><div className="mt-3 flex justify-between text-xs text-muted"><span>Promised {o.promised}</span><span>Predicted {o.predicted}</span></div></div>)}</Card></section></div>
<section className="mt-10 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-5"><SectionHeading eyebrow="Trend" title="On-time receipts" description="Rolling weekly view from sample supplier receipts."/><PerformanceChart/></Card><div><SectionHeading eyebrow="Supplier pulse" title="Supplier performance at a glance" action={<Button href="/suppliers" variant="ghost">View scorecards <ArrowRight size={15}/></Button>}/><DataTable headers={["Supplier","On-time","Lead-time variance","Quality","Segment"]} rows={["Bharat Fasteners Pvt Ltd","Precision Components","Western Steel Works"].map((name,i)=>{const d=[["72%","2.8d","2","Bottleneck"],["91%","1.1d","0","Strategic"],["84%","1.7d","1","Leverage"]][i];return <tr key={name} className="border-b border-line last:border-0"><td className="px-4 py-4 font-semibold">{name}</td><td className="px-4 py-4">{d[0]}</td><td className="px-4 py-4">{d[1]}</td><td className="px-4 py-4">{d[2]}</td><td className="px-4 py-4"><StatusPill risk={i===0?"at-risk":"on-track"}/></td></tr>})}/></section>
</AppShell>}